### ISSUE TITLE
Feature Request : constructor parameter for silent dom creation

### ISSUE THREAD

**Issue by homerrbc** [ChukwuEmekaAjah/beautiful-dom#10]
The constructor is loud. I don't need to see "all available tags are [ ....]" every time the object is created. Can you put a `boolean` parameter in the constructor to silence this?

**Comment by ChukwuEmekaAjah** [comment]
Hello @homerrbc just seeing this, I will look into it. Thank you.

**Comment by ChukwuEmekaAjah** [comment]
The unnecessary console loggings have been removed. Once again, thanks for bringing this to my attention.
